name: Build
on:
  pull_request:
    branches: [main]
jobs:
  build-extension:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: build
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: extension
          load: true
          cache-from: type=gha,scope=extension
          cache-to: type=gha,mode=max,scope=extension
      - name: Build testable docker image
        uses: docker/build-push-action@v2
        with:
          context: extension
          load: true
          cache-from: type=gha,scope=extension
          cache-to: type=gha,mode=max,scope=extension
          tags: ${{ env.DOCKER_IMAGE }}
          target: build
      - name: Run lint-check
        run: |
          docker run --name lint-check $DOCKER_IMAGE make lint-check-ci
          docker cp lint-check:/app/lint-check-results.json ./extension/lint-check-results.json
      - name: Upload lint-check results
        uses: kibalabs/github-action-create-annotations@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          json-file-path: ./extension/lint-check-results.json
          check-name: extension-lint-check
          fail-on-error: false
          path-prefix: ./extension/
      - name: Run type-check
        run: |
          docker run --name type-check $DOCKER_IMAGE make type-check-ci
          docker cp type-check:/app/type-check-results.json ./extension/type-check-results.json
      - name: Upload type-check results
        uses: kibalabs/github-action-create-annotations@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          json-file-path: ./extension/type-check-results.json
          check-name: extension-type-check
          fail-on-error: false
          path-prefix: ./extension/
